version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: evoluum
      POSTGRES_PASSWORD: evoluum123
      POSTGRES_DB: evoluum_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://evoluum:evoluum123@db:5432/evoluum_db
    ports:
      - "8000:8000"

volumes:
  db_data:
